# Generated by Django 6.0.6 on 2026-06-28 17:47

import django.core.validators
import shops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/', validators=[shops.models.validate_logo_image]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepali mobile number (e.g. 98XXXXXXXX or 97XXXXXXXX).', regex='^(98|97)\\d{8}$')]),
        ),
    ]
